// Generated by npm run sync:og. Images are served directly from public/og.
export const ogImages: Record<string, string> = {
  "/interludes/veil.png": "/og/056ebb8d761f7f6b.jpg",
  "/interludes/hands.png": "/og/fd55bc5cd7e62aa7.jpg",
  "/interludes/toast.png": "/og/6af25ed59e2062f3.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/settings/collage-1-019dce16-40dc-45b2-b88b-8c1f69af52fa.png": "/og/3091e2e993ab7990.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/settings/collage-2-cb347136-6737-47df-ba97-88d46f8f943d.png": "/og/8170933525359e96.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/settings/about-eb5fc744-59c6-4cc3-8d51-e36c964a0938.png": "/og/a93f577764dbb229.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1788905664023-lu4cln.png": "/og/5f75df5d26430e1d.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1788907283260-51hkjn.png": "/og/f877fa3877bcb782.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1788904881067-zzdjag.png": "/og/9d83cb5dac4d297b.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1788904189993-2vuj6f.png": "/og/7ff47a5021d9112c.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1780775886627-rpzaxf.png": "/og/6313d25e5af10af2.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1788909063313-p6e1gm.png": "/og/9e5b502f24815c0c.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1780773914987-v7v86j.png": "/og/e39b68b02d023c6b.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1780775965258-hi1g9.png": "/og/003b74e06c751406.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/portfolio/1788905416664-b4hr4.png": "/og/5e40ab10e4818262.jpg",
  "https://api-supabase.arody.cloud/storage/v1/object/public/oniria/blog/1788911434564-nomq89v.png": "/og/252cfe0a293084c6.jpg"
};
