import nextEnv from '@next/env';
import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';

nextEnv.loadEnvConfig(process.cwd());
const origin = process.env.NEXT_PUBLIC_SUPABASE_URL;
const client = createClient(origin, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY, {
  db: { schema: 'oniria' }, auth: { persistSession: false, autoRefreshToken: false },
});
const results = await Promise.all([
  client.from('settings').select('collage_image_1_url,collage_image_2_url,about_image_url,hero_background_type,hero_background_url').limit(1).single(),
  client.from('portfolio_projects').select('cover_image_url').eq('status', 'published'),
  client.from('blog_posts').select('cover_image_url').eq('status', 'published'),
]);
for (const { error } of results) if (error) throw new Error(error.message);
const settings = results[0].data;
const sources = new Set([
  '/interludes/veil.png', '/interludes/hands.png', '/interludes/toast.png',
  settings.collage_image_1_url, settings.collage_image_2_url, settings.about_image_url,
  settings.hero_background_type === 'image' ? settings.hero_background_url : null,
  ...results.slice(1).flatMap(({ data }) => data.map(row => row.cover_image_url)),
].filter(Boolean));
const images = {};
await mkdir('public/og', { recursive: true });
for (const source of sources) {
  let input;
  if (source.startsWith('/interludes/') && !source.includes('..')) {
    input = await readFile(`public${source}`);
  } else {
    const url = new URL(source);
    if (url.origin !== new URL(origin).origin || !url.pathname.startsWith('/storage/v1/object/public/oniria/')) {
      throw new Error('OG source must be an ONIRIA public Storage image');
    }
    const response = await fetch(url, { redirect: 'error', signal: AbortSignal.timeout(20000) });
    if (!response.ok || !response.headers.get('content-type')?.startsWith('image/')) throw new Error(`OG download failed: ${response.status}`);
    input = Buffer.from(await response.arrayBuffer());
  }
  const output = await sharp(input).rotate().resize(1200, 630, { fit: 'cover' }).jpeg({ quality: 80, progressive: true }).toBuffer();
  const filename = createHash('sha256').update(output).digest('hex').slice(0, 16) + '.jpg';
  await writeFile(`public/og/${filename}`, output);
  images[source] = `/og/${filename}`;
}
await writeFile('src/lib/ogImages.ts', '// Generated by npm run sync:og. Images are served directly from public/og.\nexport const ogImages: Record<string, string> = '+JSON.stringify(images, null, 2)+';\n');
console.log(`Saved ${sources.size} local OG images (1200 × 630 JPEG).`);
