begin;
alter table oniria.settings add column if not exists translations jsonb not null default '{}'::jsonb check (jsonb_typeof(translations) = 'object');
alter table oniria.portfolio_projects add column if not exists translations jsonb not null default '{}'::jsonb check (jsonb_typeof(translations) = 'object');
alter table oniria.blog_posts add column if not exists translations jsonb not null default '{}'::jsonb check (jsonb_typeof(translations) = 'object');
update oniria.settings set translations = $json${"es": {"site_description": "Creemos algo para recordar", "hero_subtitle": "BODAS", "interlude_1_quote": "Recuerda siempre", "interlude_1_accent": "Recuerda", "interlude_1_subtitle": "— La filosofía de Oniria", "interlude_2_quote": "Momentos para amar", "interlude_2_accent": "amar", "interlude_2_subtitle": "— Recuerdos para siempre", "philosophy_phrase_1": "No fotografiamos bodas. Inmortalizamos la forma en que se miran cuando creen que nadie los ve.", "philosophy_phrase_2": "Cada encuadre es una decisión emocional. Buscamos la verdad en lo efímero, la belleza en lo invisible.", "philosophy_phrase_3": "Creamos relatos visuales que se sienten como recuerdos propios — íntimos, eternos, irrepetibles."}, "en": {"site_description": "Let's create something to remember", "hero_subtitle": "WEDDINGS", "philosophy_phrase_1": "We don't photograph weddings. We immortalize the way they look at each other when they think no one is watching.", "philosophy_phrase_2": "Every frame is an emotional decision. We seek truth in the fleeting, beauty in the invisible.", "philosophy_phrase_3": "We craft visual narratives that feel like your own memories — intimate, eternal, unrepeatable."}}$json$::jsonb || translations where id = '6cce6c5f-2b1d-4236-96d2-b65e03786900';
update oniria.portfolio_projects set translations = '{"es":{"title":"Tráiler de boda"}}'::jsonb || translations where title = 'Wedding Trailer';
update oniria.blog_posts set translations = $json${"en": {"title": "Wedding Rings to Last Forever", "excerpt": "This is our first post.", "content": "<h1>What You Should Know</h1><p>This is a blog post.</p><p></p>", "category": "video, weddings, photography"}, "es": {"title": "Anillos de boda para siempre", "excerpt": "Este es nuestro primer artículo.", "content": "<h1>Lo que debes saber</h1><p>Este es un artículo del blog.</p><p></p>", "category": "video, bodas, fotografía"}}$json$::jsonb || translations where id = 'efdc097f-5643-4415-9cb8-8222326da91f' and title = 'Anillos de Boda para siempre';
notify pgrst, 'reload schema';
commit;
